name: release

on:
  push:
    branches:
      - main

env:
  GITHUB_REGISTRY_TOKEN: ${{ secrets.PACKAGE_REGISTRY_ACCESS_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: yarn
          node-version-file: .nvmrc
      - run: yarn install --frozen-lockfile --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${GITHUB_REGISTRY_TOKEN}
      - run: echo "//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}" > .npmrc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: changesets/action@cd8d86bdc84df7dda52db54d26a4d0c9d3c55f76
        with:
          version: yarn version
          publish: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
